### ISSUE TITLE
Failed to build xcode project as Producer

### ISSUE THREAD

**Issue by dwirandytlvk** [spotify/XCRemoteCache#195]
**My integration setup**

[x] CocoaPods cocoapods-xcremotecache plugin
[ ] Automatic integration using `xcprepare integrate ...`
[ ] Manual integration
[ ] Carthage

**Expected/desired behavior**
Can build producer mode

**Minimal reproduction of the problem with instructions**
run with xcodebuild
```
xcodebuild ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO  \
		-workspace "tvlk.xcworkspace" \
        -scheme "Tvlk Staging" -configuration "Debug" CODE_SIGNING_ALLOWED=NO \
        -sdk "iphonesimulator" \
        clean build | xcpretty
```

**Producer Logs**
<details>
  <pre> Timestamp               Ty Process[PID:TID]
2023-04-03 13:00:55.606 E  xclibtool[86958:9db3c] Failed with: missingOutput. Args: ["/Users/dwi.herdinanto/ios-product/Tvlk/tools/xcremotecache/xclibtool", "-V"]
2023-04-03 13:01:21.283 I  xclibtool[87117:9df04] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:21.533 I  xcpostbuild[87125:9df15] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:21.537 I  xcpostbuild[87125:9df15] (youtube-ios-player-helper) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:21.537 I  xcpostbuild[87125:9df15] (youtube-ios-player-helper) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:21.537 I  xcpostbuild[87125:9df15] (youtube-ios-player-helper) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/youtube-ios-player-helper/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/youtube-ios-player-helper
2023-04-03 13:01:21.537 I  xcpostbuild[87125:9df15] (youtube-ios-player-helper) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:21.709 I  xcpostbuild[87125:9df15] (youtube-ios-player-helper) Making upload request to https://mobxcrc.mob.com/file/248013d8ca27a679008084978db72034.zip with 3 retries.
2023-04-03 13:01:21.759 I  xclibtool[87128:9df2c] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:21.829 I  xcswiftc[87129:9df3a] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:21.830 Df xcswiftc[87129:9df3a] Fallbacking to compilation using swiftc.
2023-04-03 13:01:21.982 I  xcpostbuild[87133:9df5b] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:21.986 I  xcpostbuild[87133:9df5b] (nanopb) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:21.986 I  xcpostbuild[87133:9df5b] (nanopb) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:21.986 I  xcpostbuild[87133:9df5b] (nanopb) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/nanopb/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/nanopb
2023-04-03 13:01:21.986 I  xcpostbuild[87133:9df5b] (nanopb) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:22.204 I  xcpostbuild[87133:9df5b] (nanopb) Making upload request to https://mobxcrc.mob.com/file/414f6cfe33c76b17e1bea32d264f9d13.zip with 3 retries.
2023-04-03 13:01:23.124 I  xcpostbuild[87125:9df18] (youtube-ios-player-helper) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:23.132 I  xcpostbuild[87133:9df60] (nanopb) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:26.494 I  xcswiftc[87403:9e166] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:26.497 Df xcswiftc[87403:9e166] Fallbacking to compilation using swiftc.
2023-04-03 13:01:26.845 I  xclibtool[87421:9e1b2] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:27.174 I  xcpostbuild[87438:9e1f5] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:27.177 I  xcpostbuild[87438:9e1f5] (libwebp) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:27.177 I  xcpostbuild[87438:9e1f5] (libwebp) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:27.177 I  xcpostbuild[87438:9e1f5] (libwebp) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/libwebp/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/libwebp
2023-04-03 13:01:27.177 I  xcpostbuild[87438:9e1f5] (libwebp) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:28.523 I  xcpostbuild[87438:9e1f5] (libwebp) Making upload request to https://mobxcrc.mob.com/file/0fad954556be0073646beab4e7f72328.zip with 3 retries.
2023-04-03 13:01:30.617 I  xcpostbuild[87438:9e338] (libwebp) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 3.
2023-04-03 13:01:32.057 I  xclibtool[87512:9e418] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:32.396 I  xcpostbuild[87526:9e44c] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:32.399 I  xcpostbuild[87526:9e44c] (Xendit) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:32.400 I  xcpostbuild[87526:9e44c] (Xendit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:32.400 I  xcpostbuild[87526:9e44c] (Xendit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/Xendit/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/Xendit
2023-04-03 13:01:32.400 I  xcpostbuild[87526:9e44c] (Xendit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:32.744 I  xcpostbuild[87526:9e44c] (Xendit) Making upload request to https://mobxcrc.mob.com/file/e5d0517ef60a2b28360ccd3e87e65af8.zip with 3 retries.
2023-04-03 13:01:33.244 I  xcpostbuild[87133:9e01c] (nanopb) Making upload request to https://mobxcrc.mob.com/file/414f6cfe33c76b17e1bea32d264f9d13.zip with 2 retries.
2023-04-03 13:01:33.279 I  xcpostbuild[87125:9df18] (youtube-ios-player-helper) Making upload request to https://mobxcrc.mob.com/file/248013d8ca27a679008084978db72034.zip with 2 retries.
2023-04-03 13:01:33.290 I  xcpostbuild[87133:9e01c] (nanopb) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
2023-04-03 13:01:33.320 I  xcpostbuild[87125:9df18] (youtube-ios-player-helper) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
2023-04-03 13:01:33.466 I  xcpostbuild[87526:9e44f] (Xendit) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:36.594 I  xclibtool[87619:9e605] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:37.102 I  xcpostbuild[87639:9e665] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:37.105 I  xcpostbuild[87639:9e665] (lottie-ios) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:37.105 I  xcpostbuild[87639:9e665] (lottie-ios) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:37.105 I  xcpostbuild[87639:9e665] (lottie-ios) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/lottie-ios/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/lottie-ios
2023-04-03 13:01:37.106 I  xcpostbuild[87639:9e665] (lottie-ios) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:37.311 I  xcswiftc[87651:9e68f] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:37.311 Df xcswiftc[87651:9e68f] Fallbacking to compilation using swiftc.
2023-04-03 13:01:38.444 I  xclibtool[87704:9e72c] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:38.591 I  xcpostbuild[87709:9e747] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:38.594 I  xcpostbuild[87709:9e747] (TVLMasonry) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:38.594 I  xcpostbuild[87709:9e747] (TVLMasonry) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:38.594 I  xcpostbuild[87709:9e747] (TVLMasonry) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/TVLMasonry/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/TVLMasonry
2023-04-03 13:01:38.594 I  xcpostbuild[87709:9e747] (TVLMasonry) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:38.800 I  xcpostbuild[87709:9e747] (TVLMasonry) Making upload request to https://mobxcrc.mob.com/file/c7818ebba957a0551b354a0efc649a99.zip with 3 retries.
2023-04-03 13:01:38.855 I  xcpostbuild[87639:9e665] (lottie-ios) Making upload request to https://mobxcrc.mob.com/file/90f0bd866f5109f818178d62ab17d7e7.zip with 3 retries.
2023-04-03 13:01:39.048 I  xcpostbuild[87709:9e779] (TVLMasonry) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:39.108 I  xcpostbuild[87639:9e669] (lottie-ios) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 3.
2023-04-03 13:01:39.127 I  xcswiftc[87736:9e79f] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:39.128 Df xcswiftc[87736:9e79f] Fallbacking to compilation using swiftc.
2023-04-03 13:01:39.139 I  xclibtool[87739:9e7a4] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:39.223 I  xcpostbuild[87747:9e7bc] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:39.225 I  xcpostbuild[87747:9e7bc] (TVLStorage) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:39.225 I  xcpostbuild[87747:9e7bc] (TVLStorage) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:39.226 I  xcpostbuild[87747:9e7bc] (TVLStorage) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../Modules/TVLStorage/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Modules/TVLStorage
2023-04-03 13:01:39.226 I  xcpostbuild[87747:9e7bc] (TVLStorage) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:39.477 I  xcpostbuild[87747:9e7bc] (TVLStorage) Making upload request to https://mobxcrc.mob.com/file/c38ed1ffd6da299c005769244880ca18.zip with 3 retries.
2023-04-03 13:01:39.711 I  xcpostbuild[87747:9e7bd] (TVLStorage) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:40.264 I  xcswiftc[87763:9e838] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:40.264 Df xcswiftc[87763:9e838] Fallbacking to compilation using swiftc.
2023-04-03 13:01:40.635 I  xcpostbuild[87438:9e1f7] (libwebp) Making upload request to https://mobxcrc.mob.com/file/0fad954556be0073646beab4e7f72328.zip with 2 retries.
2023-04-03 13:01:40.635 I  xcswiftc[87784:9e885] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:40.636 Df xcswiftc[87784:9e885] Fallbacking to compilation using swiftc.
2023-04-03 13:01:40.694 I  xcpostbuild[87438:9e1f7] (libwebp) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 2.
2023-04-03 13:01:43.158 I  xclibtool[87839:9e952] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:43.435 I  xcpostbuild[87133:9e01c] (nanopb) Making upload request to https://mobxcrc.mob.com/file/414f6cfe33c76b17e1bea32d264f9d13.zip with 1 retries.
2023-04-03 13:01:43.461 I  xcpostbuild[87125:9e01f] (youtube-ios-player-helper) Making upload request to https://mobxcrc.mob.com/file/248013d8ca27a679008084978db72034.zip with 1 retries.
2023-04-03 13:01:43.472 I  xcpostbuild[87847:9e978] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:43.474 I  xcpostbuild[87847:9e978] (Sift) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:43.474 I  xcpostbuild[87847:9e978] (Sift) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:43.474 I  xcpostbuild[87847:9e978] (Sift) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/Sift/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/Sift
2023-04-03 13:01:43.474 I  xcpostbuild[87847:9e978] (Sift) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:43.478 I  xcpostbuild[87133:9e4a8] (nanopb) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 1.
2023-04-03 13:01:43.499 I  xcpostbuild[87125:9e4ab] (youtube-ios-player-helper) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 1.
2023-04-03 13:01:43.608 I  xclibtool[87856:9e988] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:43.648 I  xcpostbuild[87526:9e475] (Xendit) Making upload request to https://mobxcrc.mob.com/file/e5d0517ef60a2b28360ccd3e87e65af8.zip with 2 retries.
2023-04-03 13:01:43.666 I  xcpostbuild[87847:9e978] (Sift) Making upload request to https://mobxcrc.mob.com/file/760375ed79e90e21f749fa79874d82d6.zip with 3 retries.
2023-04-03 13:01:43.696 I  xcpostbuild[87526:9e475] (Xendit) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
2023-04-03 13:01:43.726 I  xclibtool[87860:9e996] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:43.802 I  xcpostbuild[87864:9e9a3] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:43.804 I  xcpostbuild[87864:9e9a3] (Starscream) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:43.804 I  xcpostbuild[87864:9e9a3] (Starscream) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:43.804 I  xcpostbuild[87864:9e9a3] (Starscream) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/Starscream/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/Starscream
2023-04-03 13:01:43.804 I  xcpostbuild[87864:9e9a3] (Starscream) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:43.912 I  xcpostbuild[87847:9e995] (Sift) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:44.076 I  xcpostbuild[87872:9e9cb] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:44.078 I  xcpostbuild[87872:9e9cb] (SnapKit) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:44.078 I  xcpostbuild[87872:9e9cb] (SnapKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:44.078 I  xcpostbuild[87872:9e9cb] (SnapKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/SnapKit/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods/SnapKit
2023-04-03 13:01:44.078 I  xcpostbuild[87872:9e9cb] (SnapKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:44.121 I  xcpostbuild[87864:9e9a3] (Starscream) Making upload request to https://mobxcrc.mob.com/file/e41a8fa4e78b3c09677ee4cfa9c53d58.zip with 3 retries.
2023-04-03 13:01:44.292 I  xcpostbuild[87864:9e9d1] (Starscream) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:44.341 I  xcpostbuild[87872:9e9cb] (SnapKit) Making upload request to https://mobxcrc.mob.com/file/fbf5912ef316b616d1e3a075910bf153.zip with 3 retries.
2023-04-03 13:01:44.616 I  xcpostbuild[87872:9e9ec] (SnapKit) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:47.687 I  xclibtool[87893:9ea45] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:47.752 I  xcpostbuild[87897:9ea56] Extra config override failed with missingConfigurationFile(user.rcinfo -- file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/). Skipping extra configuration
2023-04-03 13:01:47.754 I  xcpostbuild[87897:9ea56] (TVLIconKit) Found url to remapp: file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products/. Remapping: /Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Tvlk-agudacapbxqtnlcqyowliwglivql/Build/Products
2023-04-03 13:01:47.754 I  xcpostbuild[87897:9ea56] (TVLIconKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Pods
2023-04-03 13:01:47.754 I  xcpostbuild[87897:9ea56] (TVLIconKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../Modules/TVLIconKit/. Remapping: /Users/dwi.herdinanto/ios-product/Tvlk/Modules/TVLIconKit
2023-04-03 13:01:47.754 I  xcpostbuild[87897:9ea56] (TVLIconKit) Found url to remapp: file:///Users/dwi.herdinanto/ios-product/Tvlk/Pods/../. Remapping: /Users/dwi.herdinanto/ios-product/Traveloka
2023-04-03 13:01:47.986 I  xcpostbuild[87897:9ea56] (TVLIconKit) Making upload request to https://mobxcrc.mob.com/file/d061f5a916aa2c07971178e6955ff3c8.zip with 3 retries.
2023-04-03 13:01:48.257 I  xcpostbuild[87897:9ea57] (TVLIconKit) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 3.
2023-04-03 13:01:49.139 I  xcpostbuild[87709:9e779] (TVLMasonry) Making upload request to https://mobxcrc.mob.com/file/c7818ebba957a0551b354a0efc649a99.zip with 2 retries.
2023-04-03 13:01:49.184 I  xcpostbuild[87709:9e779] (TVLMasonry) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
2023-04-03 13:01:49.190 I  xcpostbuild[87639:9e79e] (lottie-ios) Making upload request to https://mobxcrc.mob.com/file/90f0bd866f5109f818178d62ab17d7e7.zip with 2 retries.
2023-04-03 13:01:49.240 I  xcpostbuild[87639:9e780] (lottie-ios) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 2.
2023-04-03 13:01:49.763 I  xcpostbuild[87747:9e7bf] (TVLStorage) Making upload request to https://mobxcrc.mob.com/file/c38ed1ffd6da299c005769244880ca18.zip with 2 retries.
2023-04-03 13:01:49.813 I  xcpostbuild[87747:9e7e6] (TVLStorage) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
2023-04-03 13:01:50.849 I  xcpostbuild[87438:9e35b] (libwebp) Making upload request to https://mobxcrc.mob.com/file/0fad954556be0073646beab4e7f72328.zip with 1 retries.
2023-04-03 13:01:50.888 I  xcpostbuild[87438:9e35b] (libwebp) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 1.
2023-04-03 13:01:53.644 I  xcpostbuild[87133:9e01c] (nanopb) Making upload request to https://mobxcrc.mob.com/file/414f6cfe33c76b17e1bea32d264f9d13.zip with 0 retries.
2023-04-03 13:01:53.680 I  xcpostbuild[87125:9e4be] (youtube-ios-player-helper) Making upload request to https://mobxcrc.mob.com/file/248013d8ca27a679008084978db72034.zip with 0 retries.
2023-04-03 13:01:53.688 E  xcpostbuild[87133:9e4a8] (nanopb) Upload request failed: unsuccessfulResponse(status: 404)
2023-04-03 13:01:53.688 E  xcpostbuild[87133:9df5b] (nanopb) Postbuild step failed with error: unsuccessfulResponse(status: 404)
2023-04-03 13:01:53.688 E  xcpostbuild[87133:9df5b] (nanopb) Postbuild step failed unsuccessfulResponse(status: 404)
2023-04-03 13:03:37.688 E  xclibtool[88017:9f1c1] Missing 'output' argument. Args: ["/Users/dwi.herdinanto/Downloads/XCRemoteCache-macOS-x86_64-v0.3.19/xclibtool"]
2023-04-03 13:03:50.336 E  xclibtool[88027:9f239] Missing 'output' argument. Args: ["/Users/dwi.herdinanto/Downloads/XCRemoteCache-macOS-x86_64-v0.3.19/xclibtool"]</pre>
</details>

**Consumer Logs**

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Pods/Carthage file**

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Environment**

* **XCRemoteCache:** 0.3.21
* **cocoapods-xcremotecache:** X.Y.Z 

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Others**

**Comment by dwirandytlvk** [comment]
cc: @polac24

**Comment by polac24** [comment]
I would check first why the server returns 413 in the upload (too large file)

```
2023-04-03 13:01:50.849 I  xcpostbuild[87438:9e35b] (libwebp) Making upload request to https://mobxcrc.mob.com/file/0fad954556be0073646beab4e7f72328.zip with 1 retries.
2023-04-03 13:01:50.888 I  xcpostbuild[87438:9e35b] (libwebp) Upload request failed with unsuccessfulResponse(status: 413). Left retries: 1.
```

or 404:
```
2023-04-03 13:01:49.139 I  xcpostbuild[87709:9e779] (TVLMasonry) Making upload request to https://mobxcrc.mob.com/file/c7818ebba957a0551b354a0efc649a99.zip with 2 retries.
2023-04-03 13:01:49.184 I  xcpostbuild[87709:9e779] (TVLMasonry) Upload request failed with unsuccessfulResponse(status: 404). Left retries: 2.
```

**Comment by dwirandytlvk** [comment]
@polac24 i'm not sure how to test it and find the root cause,

can i use curl or postman to replicate it?

**Comment by polac24** [comment]
Yes, curl is enough. After a build, in DerivedData, find a file with the same filename (e.g. `c7818ebba957a0551b354a0efc649a99.zip`) and make a put request to the address, something like:
```
curl -X PUT -d @/your/file/path/c7818ebba957a0551b354a0efc649a99.zip https://mobxcrc.mob.com/file/c7818ebba957a0551b354a0efc649a99.zip -v
```

**Comment by dwirandytlvk** [comment]
Hi @polac24 sorry for late update, i try to find the .zip file but i can not find it inside build directory

```
2023-05-15 14:41:21.628 E  xcpostbuild[23123:202c5] (TVLMasonry) Postbuild step failed with error: Error Domain=NSCocoaErrorDomain Code=260 "The file “x86_64” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Traveloka-babfgfgiwckmrifqhpynvvesrxsr/Index.noindex/Build/Intermediates.noindex/TVLMasonry.build/Debug-iphonesimulator/TVLMasonry.build/Objects-normal/x86_64, NSFilePath=/Users/dwi.herdinanto/Library/Developer/Xcode/DerivedData/Traveloka-babfgfgiwckmrifqhpynvvesrxsr/Index.noindex/Build/Intermediates.noindex/TVLMasonry.build/Debug-iphonesimulator/TVLMasonry.build/Objects-normal/x86_64, NSUnderlyingError=0x600000714420 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

I don't think i have changed my xcode setting

**Comment by polac24** [comment]
Yes:
* Xcode (starting Xcode 13) builds the project twice: once for build and once for "indexing" that powers code completion
* Index.noindex corresponds to the workspace for the "indexing build"
* Xcode sets then `ACTION=indexbuild`
* I recommend building and uploading all artifacts from the "standard" `xcodebuild` - then the `ACTION=indexbuild` flow is not triggered.

**Comment by dwirandytlvk** [comment]
Hi @polac24 i have tried it to build using xcodebuild and i got the output

```
2023-05-16 15:19:33.812 I  xcprepare[20759:253e2] Network request failed with unsuccessful code 404
2023-05-16 15:19:33.812 I  xcprepare[20759:253d8] No artifacts available
2023-05-16 15:20:18.382 E  xclibtool[21263:25a9f] Failed with: missingOutput. Args: ["/Users/dwi.herdinanto/ios/Traveloka/tools/xcremotecache/xclibtool", "-V"]
```

i am not sure what is happened, do you know why?

**Comment by polac24** [comment]
That is probably because of Xcode 14.3, should be fixed in #205

**Comment by dwirandytlvk** [comment]
That PR seems work, but i still have problem since i can not send artifact to my server

```
2023-05-17 13:46:17.143 I  xcpostbuild[36453:54185] (youtube-ios-player-helper) Making upload request to https://mobxcrc.mob.development-traveloka.com/file/a4b086c36bfa25ee9ed1f2b5888f6499.zip with 0 retries.
2023-05-17 13:46:17.210 E  xcpostbuild[36453:5467a] (youtube-ios-player-helper) Upload request failed: unsuccessfulResponse(status: 404)
2023-05-17 13:46:17.211 E  xcpostbuild[36453:54182] (youtube-ios-player-helper) Postbuild step failed with error: unsuccessfulResponse(status: 404)
2023-05-17 13:46:17.211 E  xcpostbuild[36453:54182] (youtube-ios-player-helper) Postbuild step failed unsuccessfulResponse(status: 404)
```

i also trying to upload manually via curl
```
curl -X PUT -d ./a4b086c36bfa25ee9ed1f2b5888f6499.zip https://mobxcrc.mob.com/file/a4b086c36bfa25ee9ed1f2b5888f6499.zip
```

output:
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.1</center>
</body>
</html>
```

**Comment by polac24** [comment]
since `curl` fails, that looks like a problem with your backend nginx.
